### ISSUE TITLE
Work up the information of the Moderation-Events

### ISSUE THREAD

**Issue by Develeon64** [terillos-development/twitchd#11]
- [ ] msg_id is always empty
- [ ] target_user_login is always empty
- [ ] channel is not provided
- [ ] unmod doesn't fire event
- [ ] special look on new unban request system feature (creating request doesn't fire event; accept/decline information has different defination)

Suggestion: implement a custom Interface with gathered information, containing:
- Type of action ([un]ban, [un]timeout, etc)
- Channel_Name, where the event happened
- Moderator performing the action
- Affected User
- Period in seconds, if Timeout
- Reason given by Moderator
- Message (content) the action was performed on

**Comment by richardhofmaenner** [comment]
Hi there,

I've reworked the returned info. Now you will get:

- channel_id
- from_id
- target_id
- type of action
- timeout_time (if available)
- reason (if available)

According to my tests the PubSub-Api does not respond at an unmod-Events. That's something odd with twitch itself which I can't fix.

Also the context of messages why a user has been banned/timeouted can't be displayed with the pubsub API.

And finally the new unban-request feature seems not to have an public api.

This issue will be resolved with the merging of #17 and the release of the prerelease 0.2

**Comment by richardhofmaenner** [comment]
Has been merged with #17
